# docker-compose.yml #
version: "3.4"
services:
  app:
    image: php:alpine
    volumes:
      - "./:/app"
    working_dir: /app
    command: "php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - 8000:8000
    build:
      context: docker/php
      dockerfile: dev.Dockerfile
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - "db-mysql:/var/lib/mysql"
volumes:
  db-mysql: {}
